#!/usr/bin/env bash

set -ue

output="$(git tag --list --sort=-v:refname 'n*.*')"

while read -r s; do
	if [[ $s != *-dev ]]; then
		git checkout --quiet "$s"
		printf '%s\n' "$s"
		exit 0
	fi
done <<<"$output"
