#!/usr/bin/env bash

set -ue

# ./update_version
# . ./package_version
# printf '%s\n' "$PACKAGE_VERSION"

current="$(latest_git_tag)"
since_last="$(git rev-list --count HEAD)"

if [[ $current =~ ^[vV]?[0-9]+\.[0-9]+$ ]]; then
	current="$current.0"
fi

if [[ $since_last == 0 ]]; then
	printf %s "$current"
else
	printf %s "$current-r$since_last"
fi
