#!/usr/bin/env bash

current="$(latest_git_tag)"
current="${current#sox-}"
since_last="$(git rev-list --count HEAD)"
if [[ $since_last == 0 ]]; then
	printf %s "$current"
else
	printf %s "$current-r$since_last"
fi
