#!/usr/bin/env bash
# shellcheck disable=SC2086,SC2206

set -f

# This wrapper exists because some projects like to pass -E to lld, which lld doesn't understand.

args=($AB_LDFLAGS)
for a in "$@"; do
	if [ "$a" != -E ]; then
		args+=("$a")
	fi
done

exec ld.lld "${args[@]}" $AB_LDFLAGS_AFTER
