#!/usr/bin/env bash
# shellcheck disable=SC2086

case "${AB_CC:-}" in
# Bypass the logic here if AB_CC is ab-clang
*ab-clang*)
	exec ${AB_CC} "$@"
	exit
	;;
# Prevent infinite recursion.
*ab-gcc*)
	echo 1>&2 "ab-gcc: error: AB_CC is set to ab-gcc, causing infinite recursion"
	exit 1
	;;
esac

set -f

args=()
for a in "$@"; do
	case "$a" in
	# Some projects hardcode -O3 for no good reason; -O2 is as fast and smaller.
	-O3) args+=("-O${AB_OPT_LEVEL:-2}") ;;
	-I/usr/include | -L/usr/lib | -L/lib | -L/lib/)
		if [ "${AB_IGNORE_SYSTEM_PATHS:-}" = 1 ]; then
			echo 1>&2 "ab-gcc: warning: attempted to use headers/libraries from build machine: $a"
		else
			echo 1>&2 "ab-gcc: error: attempted to use headers/libraries from build machine: $a"
			echo 1>&2 "invocation:"
			printf 1>&2 '%s\n' "$*"
			exit 1
		fi
		;;
	*) args+=("$a") ;;
	esac
done

exec ${AB_CC:-x86_64-w64-mingw32-gcc} \
	$AB_CCFLAGS_BEFORE \
	"${args[@]}" \
	$AB_CCFLAGS
