#!/usr/bin/env dash

export PKG_CONFIG_LIBDIR="\
$PKG_CONFIG_PATH:\
$PKG_CONFIG_LIBDIR:\
${AB_MINGW_SYSROOT:+"$AB_MINGW_SYSROOT/x86_64-w64-mingw32/lib/pkgconfig:$AB_MINGW_SYSROOT/x86_64-w64-mingw32/share/pkgconfig"}"

export PKG_CONFIG_PATH="$PKG_CONFIG_LIBDIR"

exec pkg-config "$@"
