#!/usr/bin/env bash
# shellcheck disable=SC2086

case "${AB_CXX:-}" in
# Bypass the logic here if AB_CXX is ab-clang++
*ab-clang++*)
	exec ${AB_CXX} "$@"
	exit
	;;
# Prevent infinite recursion.
*ab-g++*)
	echo 1>&2 "ab-g++: error: AB_CXX is set to ab-g++, causing infinite recursion"
	exit 1
	;;
esac

set -f

args=()
for a in "$@"; do
	case "$a" in
	# Some projects hardcode -O3 for no good reason; -O2 is as fast and smaller.
	-O3) args+=(-O2) ;;
	-I/usr/include | -L/usr/lib | -L/lib | -L/lib/)
		if [ "${AB_IGNORE_SYSTEM_PATHS:-}" = 1 ]; then
			echo 1>&2 "ab-g++: warning: attempted to use headers/libraries from build machine: $a"
		else
			echo 1>&2 "ab-g++: error: attempted to use headers/libraries from build machine: $a"
			echo 1>&2 "invocation:"
			printf 1>&2 '%s\n' "$*"
			exit 1
		fi
		;;
	*) args+=("$a") ;;
	esac
done

exec ${AB_CXX:-x86_64-w64-mingw32-g++} \
	$AB_CXXFLAGS_BEFORE \
	"${args[@]}" \
	$AB_CXXFLAGS
