#!/usr/bin/env bash

download adplug lib/libadplug.a
install_lib binio

set_env x:-Wno-register

run autoreconf -fi
configure_install_par --with-gnu-ld --disable-{dependency-tracking,maintainer-mode}
