#!/usr/bin/env bash

download gpg-error lib/libgpg-error.a
install_lib iconv

set_env

# run autoreconf -fi
configure_install_par \
	--disable-{maintainer-mode,nls,rpath,werror,doc,tests} \
	--enable-{threads=posix,install-gpg-error-config,languages,year2038} \
	--with-gnu-ld \
	--with-libiconv-prefix="$AB_PREFIX" \
	--without-readline
