#!/usr/bin/env bash

download iconv lib/libiconv.a

version="$(ab_get_version iconv)"

set_env

apply_patches -Nbp1

configure_install_par \
	--disable-rpath \
	--enable-{nls,extra-encodings,relocatable,silent-rules}

cat >iconv.pc <<-EOF
	prefix=$AB_PREFIX
	exec_prefix=\${prefix}
	libdir=\${exec_prefix}/lib
	includedir=\${prefix}/include

	Name: iconv
	Description: libiconv
	URL: https://www.gnu.org/software/libiconv/
	Version: $version
	Libs: -L\${libdir} -liconv
	Cflags: -I\${includedir}
EOF

run install -Dm755 iconv.pc "$AB_PREFIX/lib/pkgconfig/iconv.pc"
