#!/usr/bin/env bash

download idn2 lib/libidn2.a
# On aarch64, the build process tries to execute windows executables, which fails. So we just use msys here.
msys_install
exit 0

install_lib iconv unistring

set_env -fno-lto -l:libunistring.a -DIDN2_STATIC

# AUTOPOINT=true run autoreconf -fi

# run_configure \
# --enable-{year2038,largefile} \
# --disable-{valgrind-tests,fuzzing,cfi,ubsan,asan,rpath,nls,code-coverage,gcc-warnings,doc} \
# --with-libiconv-prefix="$AB_PREFIX"} \
# --with-included-libunistring

# run ./bootstrap
# AUTOPOINT=true run autoreconf -fi
./bootstrap || {
	run touch unistring/unistr/unistring-notinline.h unistring/Makefile.in
	echo -e 'all:\ninstall:\n' >unistring/Makefile.in
	ln -s "$AB_PREFIX/lib/libunistring.la" unistring/libunistring.la
}

run ./bootstrap

configure_install_par \
	--enable-{year2038,largefile} \
	--disable-{valgrind-tests,fuzzing,cfi,ubsan,asan,rpath,nls,code-coverage,gcc-warnings,doc} \
	--with-{libiconv,libunistring}-prefix="$AB_PREFIX"} \
	--without-included-libunistring
