#!/usr/bin/env bash

download lame lib/libmp3lame.a
install_lib iconv

set_env

configure_install_par \
	--enable-{nasm,expopt} \
	--disable-{maintainer-mode,frontend,gtktest,analyzer-hooks,debug} \
	--with-libiconv-prefix="$AB_PREFIX" \
	--with-gnu-ld
