#!/usr/bin/env bash

download libffi lib/libffi.a

install_lib iconv

set_env

# run autoreconf -fi
configure_install \
	--disable-{maintainer-mode,docs,debug,multi-os-directory} \
	--enable-portable-binary
