#!/usr/bin/env bash

download theora lib/libtheora.a
install_lib ogg

set_env

run ./autogen.sh

configure_install_par \
	--disable-{doc,valgrind-testing,oggtest,vorbistest,telemetry,examples} \
	--with-{gnu-ld,ogg="$AB_PREFIX"} \
	llvm:--disable-asm
