#!/usr/bin/env bash

download vpx lib/libvpx.a

set_env c:-fno-asynchronous-unwind-tables

export LD="$CC"

# Note: This isn't a standard configure script.
run ./configure \
	--prefix="$AB_PREFIX" \
	--enable-static --disable-shared \
	--target=x86_64-win64-gcc \
	--enable-{vp8,vp9,vp9-highbitdepth,vp9-temporal-denoising,runtime-cpu-detect,postproc,pic,experimental} \
	--disable-{debug,gprof,docs,gcov,install-docs,install-bins,examples,tools,docs,unit-tests,decode-perf-tests,encode-perf-tests}

run make -j$JOBS

if [[ ! -e libvpx.a ]]; then
	run cp libvpxrc_g.a libvpxrc.a
	run cp libvpx_g.a libvpx.a
fi

run make install
