#!/usr/bin/env bash

download vpx lib/libvpx.a

set_env

# Note: This isn't a standard configure script.
run ./configure \
	--prefix="$AB_PREFIX" \
	--enable-static --disable-shared \
	--target=x86_64-win64-gcc \
	--extra-cflags="$CFLAGS" --extra-cxxflags="$CXXFLAGS" \
	--disable-{dependency-tracking,debug,gprof,gcov,install-docs,install-bins,examples,tools,docs,unit-tests,decode-perf-tests,encode-perf-tests} \
	--enable-{libs,install-libs} \
	--enable-{vp9-highbitdepth,better-hw-compatibility,vp8,vp9,postproc,vp9-postproc,error-concealment,runtime-cpu-detect} \
	--enable-{multi-res-encoding,vp9-temporal-denoising,webm-io} \
	--enable-{vp8,vp9}

# --cpu=skylake \
run make -j$JOBS

if [[ ! -e libvpx.a ]]; then
	run cp libvpxrc_g.a libvpxrc.a
	run cp libvpx_g.a libvpx.a
fi

run make install
