#!/usr/bin/env bash

download vulkan-headers include/vulkan/vulkan.h

set_env

# mkcd autobuild
# cmake_install .. \
# -DVULKAN_HPP_{SAMPLES,TESTS}_BUILD=OFF

mkcd Vulkan-Headers/autobuild
cmake_install .. -DBUILD_TESTS=OFF
