#!/usr/bin/env bash

download vvenc lib/libvvenc.a

set_env
mkcd autobuild
cmake_install .. \
	-DCMAKE_CXX_COMPILER_AR="$AR" \
	-DCMAKE_CXX_COMPILER_RANLIB="$RANLIB" \
	-DVVENC_INSTALL_FULLFEATURE_APP=OFF \
	$(if [[ -n $AB_CPU ]]; then printf %s -DVVENC_OPT_TARGET_ARCH="$AB_CPU"; fi)
